import Link from 'next/link';
import type { ReactNode } from 'react';
import { Fragment } from 'react';
import { Nav, ArrowUpRight } from '../../ui';

function Section({number,eyebrow,title,children}:{number:string;eyebrow:string;title:ReactNode;children:ReactNode}){
 return <section className="case-section site-width"><div className="case-section-intro"><span className="section-number">{number}</span><div><p className="overline">{eyebrow}</p><h2>{title}</h2></div></div>{children}</section>
}
function Dashboard(){return <div className="case-hero-visual"><div className="case-window"><div className="case-window-top"><span>FLO / DASHBOARD</span><span>FINANCIAL OVERVIEW</span></div><div className="dash-head"><div><small>FINANCIAL POSITION</small><h3>See the signals that matter.</h3></div><span>THIS MONTH</span></div><div className="dash-kpis"><div><small>CASH POSITION</small><b>Overview</b><span>Current state</span></div><div><small>RUNWAY</small><b>Signal</b><span>Needs attention</span></div><div><small>UPCOMING</small><b>Commitments</b><span>Review required</span></div></div><div className="dash-chart"><small>CASH FLOW TREND</small><i/><i/><i/><i/></div></div></div>}
function Transactions(){return <div className="case-hero-visual"><div className="case-window"><div className="case-window-top"><span>TRANSACTIONS</span><span>FILTER · SEARCH · REVIEW</span></div>{['Software subscription','Client payment','Payroll','Vendor payment'].map((x,i)=><div className="transaction-row" key={x}><b>{x}</b><span>{i===1?'Income':'Expense'}</span><span>{i===2?'Needs review':'Reviewed'}</span></div>)}</div></div>}
function Flow({items}:{items:string[]}){return <div className="system-flow">{items.map((x,i)=><Fragment key={x}><div className="flow-node"><small>{String(i+1).padStart(2,'0')}</small><b>{x}</b></div>{i<items.length-1&&<i>→</i>}</Fragment>)}</div>}
export default function FloCaseStudy(){return <><Nav/><main className="case-study flo-case">
<section className="case-hero site-width"><div className="case-kicker"><span>01 / B2B SAAS</span><span>AI · FINTECH</span></div><h1>Turn financial data<br/><span>into better decisions.</span></h1><p className="case-lead">Flo is a financial intelligence platform designed to help teams move from simply seeing their numbers to understanding what they mean and deciding what to do next.</p><div className="case-meta"><div><small>ROLE</small><b>Product Designer</b></div><div><small>SCOPE</small><b>Dashboard · Transactions · Budgets · Forecast · Scenarios</b></div><div><small>TIMELINE</small><b>2026</b></div><div><small>PLATFORM</small><b>Web</b></div></div></section>
<Section number="02" eyebrow="Core idea" title={<>From reporting<br/><em>to decision support.</em></>}><div className="three-col-copy"><div><span>01</span><h3>SEE</h3><p>Bring financial information into one clear operational view.</p></div><div><span>02</span><h3>UNDERSTAND</h3><p>Turn signals into context instead of leaving teams to interpret raw numbers.</p></div><div><span>03</span><h3>SIMULATE → ACT</h3><p>Explore scenarios and connect financial insight to the next decision.</p></div></div></Section>
<Section number="03" eyebrow="Problem" title={<>Finance teams can see the numbers.<br/><em>They struggle to act on them.</em></>}><div className="problem-grid"><div><span>01</span><h3>REACTIVE</h3><p>Issues can become visible only after a financial change has already happened.</p></div><div><span>02</span><h3>FRAGMENTED</h3><p>Transactions, budgets, forecasts, and planning create separate mental models.</p></div><div><span>03</span><h3>UNCERTAIN</h3><p>A number can show what happened without explaining why it matters or what to do next.</p></div></div></Section>
<Section number="04" eyebrow="Design direction" title={<>One connected<br/><em>mental model.</em></>}><Flow items={['TRANSACTIONS','DATA','SIGNALS','FORECAST','SCENARIOS','DECISION']}/><p className="section-note">Instead of designing each module as a separate destination, the product connects them around the financial decisions users need to make.</p></Section>
<Section number="05" eyebrow="Dashboard" title={<>See the signals<br/><em>that matter.</em></>}><Dashboard/><p className="section-note">The dashboard is designed as a decision surface: status first, context second, action next.</p></Section>
<Section number="06" eyebrow="AI experience" title={<>Put AI<br/><em>where decisions happen.</em></>}><div className="three-col-copy"><div><span>01</span><h3>SIGNAL</h3><p>Identify something that deserves attention.</p></div><div><span>02</span><h3>EXPLANATION</h3><p>Show the context behind the signal in plain language.</p></div><div><span>03</span><h3>RECOMMENDATION</h3><p>Turn the insight into a specific, actionable next step.</p></div></div><div className="case-hero-visual"><div className="case-window"><div className="case-window-top"><span>FLO / FINANCIAL SIGNAL</span><span>AI INSIGHT</span></div><h3>Cash runway · Needs attention</h3><p>Cash position is tightening against the current spending pattern.</p><div className="signal-footer">WHY THIS MATTERS&nbsp;&nbsp; → &nbsp;&nbsp;VIEW EXPLANATION</div></div></div></Section>
<Section number="07" eyebrow="Transactions" title={<>Turn transactions<br/><em>into context.</em></>}><Transactions/><div className="case-copy-grid"><p><b>FROM</b><br/>Raw activity that requires manual interpretation.</p><p><b>TO</b><br/>Categorisation, review states, and context that support downstream planning.</p></div></Section>
<Section number="08" eyebrow="Budgets" title={<>Allocate budgets<br/><em>with confidence.</em></>}><div className="feature-panel"><div><span>BUDGETS / ALLOCATION</span><h3>Make allocation visible before spending happens.</h3><p>Connect planned allocation with actual spending so teams can understand where resources are going and where attention is needed.</p></div><div className="feature-list"><div><span>01</span><b>Department allocation</b></div><div><span>02</span><b>Spend tracking</b></div><div><span>03</span><b>Variance awareness</b></div></div></div></Section>
<Section number="09" eyebrow="Forecast" title={<>See where cash flow<br/><em>is heading.</em></>}><div className="feature-panel"><div><span>FORECAST / SIGNAL</span><h3>Move from historical reporting to forward-looking visibility.</h3><p>Bring expected inflows, outflows, and existing financial context into one view so teams can see what may require attention ahead of time.</p></div><div className="feature-list"><div><span>01</span><b>Historical context</b></div><div><span>02</span><b>Current position</b></div><div><span>03</span><b>Forward view</b></div></div></div></Section>
<Section number="10" eyebrow="Scenarios" title={<>Model decisions<br/><em>before committing.</em></>}><div className="feature-panel"><div><span>SCENARIO PLANNING</span><h3>Change an assumption. See the implication.</h3><p>Create a safe space to explore possible financial decisions before they become real commitments.</p></div><div className="feature-list"><div><span>01</span><b>Baseline</b></div><div><span>02</span><b>Assumption</b></div><div><span>03</span><b>Scenario comparison</b></div></div></div></Section>
<Section number="11" eyebrow="Design system" title={<>A system built<br/><em>for financial density.</em></>}><div className="problem-grid"><div><span>TYPE</span><h3>Clear hierarchy</h3><p>Large decision headlines, compact supporting labels, and readable dense data.</p></div><div><span>COLOR</span><h3>Semantic meaning</h3><p>Color is reserved for status, emphasis, and action rather than decoration.</p></div><div><span>COMPONENTS</span><h3>Reusable patterns</h3><p>Cards, tables, filters, states, signals, and panels share consistent behaviour.</p></div></div></Section>
<Section number="12" eyebrow="Outcome" title={<>What changed<br/><em>in the product model.</em></>}><div className="question-list"><div><span>01</span><b>From dashboards to decision surfaces.</b><p>Information is organised around what users need to understand and decide.</p></div><div><span>02</span><b>From isolated modules to a connected flow.</b><p>Transactions, signals, budgets, forecasts, and scenarios reinforce one financial mental model.</p></div><div><span>03</span><b>From AI as a feature to AI as guidance.</b><p>AI is placed next to the signal it explains, with recommendations tied to the next action.</p></div></div><p className="section-note">This case study documents product and design direction. It intentionally does not claim unverified production metrics or business outcomes.</p></Section>
<section className="statement-band case-statement"><div className="site-width"><p className="overline">NEXT PROJECT</p><h2>Make every operational state<br/><span>visible.</span></h2><Link className="text-link" href="/work/scheduler">Scheduler Management <ArrowUpRight/></Link></div></section>
</main></>}
